service:
  name: predict-lambda

plugins:
  - serverless-python-requirements
provider:
  name: aws
  runtime: python3.6
  region: us-west-2
  stage: dev
  deploymentBucket:
    name: cwr-aws-lambda-test
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource:
        - "arn:aws:s3:::cwr-aws-lambda-test/*"
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource:
        - "arn:aws:secretsmanager:us-west-2:448640439519:secret:prod/aws_predict/postgres-uUwO14"

package:
  exclude:
    - "**/*"
  include:
    - "categorizer_lambda/**"

custom:
  pythonRequirements:
    dockerizePip: true
    fileName: Pipfile
    slim: false

functions:
  categorizer_lambda:
    name: categorizer_lambda
    description: >
      categorize cause of fire based on fire attributes
    handler: categorizer_lambda.main.lambda_handler
    events:
      - http:
          path: firecause
          method: POST
    environment:
      MODEL_BUCKET: cwr-aws-lambda-test
      MODEL_PIPELINE_PATH: us_wildfire_models/decission_tree_classifier.pkl
      MODEL_CLASSIFIER_PATH: us_wildfire_models/decission_tree_classifier.pkl
